
package com.ucca.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.ucca.common.ArrayOfAccount;
import com.ucca.common.ArrayOfBalance;
import com.ucca.common.ArrayOfEmployee;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UccaServicePortType", targetNamespace = "http://webservice.ucca.com")
@XmlSeeAlso({
    com.ucca.common.ObjectFactory.class,
    com.ucca.webservice.ObjectFactory.class
})
public interface UccaServicePortType {


    /**
     * 
     * @param endDate
     * @param vaildCode
     * @param startDate
     * @return
     *     returns com.ucca.common.ArrayOfEmployee
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.ucca.com")
    @RequestWrapper(localName = "queryCardIDByDate", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryCardIDByDate")
    @ResponseWrapper(localName = "queryCardIDByDateResponse", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryCardIDByDateResponse")
    public ArrayOfEmployee queryCardIDByDate(
        @WebParam(name = "vaildCode", targetNamespace = "http://webservice.ucca.com")
        String vaildCode,
        @WebParam(name = "startDate", targetNamespace = "http://webservice.ucca.com")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://webservice.ucca.com")
        String endDate);

    /**
     * 
     * @param employeeId
     * @param vaildCode
     * @return
     *     returns com.ucca.common.ArrayOfEmployee
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.ucca.com")
    @RequestWrapper(localName = "queryCardIDAndVaildCode", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryCardIDAndVaildCode")
    @ResponseWrapper(localName = "queryCardIDAndVaildCodeResponse", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryCardIDAndVaildCodeResponse")
    public ArrayOfEmployee queryCardIDAndVaildCode(
        @WebParam(name = "employeeId", targetNamespace = "http://webservice.ucca.com")
        String employeeId,
        @WebParam(name = "vaildCode", targetNamespace = "http://webservice.ucca.com")
        String vaildCode);

    /**
     * 
     * @param employeeId
     * @return
     *     returns com.ucca.common.ArrayOfEmployee
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.ucca.com")
    @RequestWrapper(localName = "queryCardID", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryCardID")
    @ResponseWrapper(localName = "queryCardIDResponse", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryCardIDResponse")
    public ArrayOfEmployee queryCardID(
        @WebParam(name = "employeeId", targetNamespace = "http://webservice.ucca.com")
        String employeeId);

    /**
     * 
     * @param endDate
     * @param employeeId
     * @param vaildCode
     * @param startDate
     * @return
     *     returns com.ucca.common.ArrayOfBalance
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.ucca.com")
    @RequestWrapper(localName = "queryBalances", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryBalances")
    @ResponseWrapper(localName = "queryBalancesResponse", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryBalancesResponse")
    public ArrayOfBalance queryBalances(
        @WebParam(name = "employeeId", targetNamespace = "http://webservice.ucca.com")
        String employeeId,
        @WebParam(name = "vaildCode", targetNamespace = "http://webservice.ucca.com")
        String vaildCode,
        @WebParam(name = "startDate", targetNamespace = "http://webservice.ucca.com")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://webservice.ucca.com")
        String endDate);

    /**
     * 
     * @param employeeId
     * @param vaildCode
     * @return
     *     returns com.ucca.common.ArrayOfAccount
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.ucca.com")
    @RequestWrapper(localName = "queryMoney", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryMoney")
    @ResponseWrapper(localName = "queryMoneyResponse", targetNamespace = "http://webservice.ucca.com", className = "com.ucca.webservice.QueryMoneyResponse")
    public ArrayOfAccount queryMoney(
        @WebParam(name = "employeeId", targetNamespace = "http://webservice.ucca.com")
        String employeeId,
        @WebParam(name = "vaildCode", targetNamespace = "http://webservice.ucca.com")
        String vaildCode);

}
